name: CI

on:
  push:
    branches: [ labweek6 ]
  pull_request:
    branches: [ labweek6 ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Upload Jest HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: jest-report
        path: ./html-report/*
